### ISSUE TITLE
 --minimum-gas-prices option not set!

### ISSUE THREAD

**Issue by xiaogan18** [coinexchain/testnets#3]
如题，请问如何解决

**Comment by zxh0** [comment]
你好，启动`cetd`时，最好通过`--minimum-gas-prices`选项指定gas price最小值；否则就会出现这条警告。目前testnet，gas price不能小于20sato.cet，也就是说加上`--minimum-gas-prices=20.0cet`即可。

**Comment by xiaogan18** [comment]
按您说的添加了参数 --minimum-gas-prices，panic了
> panic: invalid minimum gas prices: invalid decimal coin expression: 20cet
尝试了2次，结果一样，启动命令如下：
`cetd start --minimum-gas-prices 20`
`cetd start --minimum-gas-prices 20cet`

**Comment by zxh0** [comment]
@xiaogan18 抱歉，少写了小数点 :(
把选项改成这样再试试：`--minimum-gas-prices=20.0cet`

**Comment by xiaogan18** [comment]
程序可以正常启动了，但是一直无法同步数据。
## debug log
`
I[2019-10-29|16:39:48.898] Starting ABCI with Tendermint                module=main
I[2019-10-29|16:39:48.943] Starting multiAppConn                        module=proxy impl=multiAppConn
I[2019-10-29|16:39:48.943] Starting localClient                         module=abci-client connection=query impl=localClient
I[2019-10-29|16:39:48.944] Starting localClient                         module=abci-client connection=mempool impl=localClient
I[2019-10-29|16:39:48.944] Starting localClient                         module=abci-client connection=consensus impl=localClient
I[2019-10-29|16:39:48.944] Starting EventBus                            module=events impl=EventBus
I[2019-10-29|16:39:48.944] Starting PubSub                              module=pubsub impl=PubSub
I[2019-10-29|16:39:48.956] Starting IndexerService                      module=txindex impl=IndexerService
I[2019-10-29|16:39:48.956] ABCI Handshake App Info                      module=consensus height=0 hash= software-version= protocol-version=0
I[2019-10-29|16:39:48.956] ABCI Replay Blocks                           module=consensus appHeight=0 storeHeight=0 stateHeight=0
I[2019-10-29|16:39:48.962] asserted all invariants                      module=x/crisis duration=523.274µs height=0
I[2019-10-29|16:39:48.967] Completed ABCI Handshake - Tendermint and App are synced module=consensus appHeight=0 appHash=
I[2019-10-29|16:39:48.967] Version info                                 module=node software=0.32.2 block=10 p2p=7
I[2019-10-29|16:39:48.967] This node is not a validator                 module=consensus addr=749FB33317285CF866A37222FF9FBEC57ABA54FE pubKey=PubKeyEd25519{70260283D9F5A85B4EC53C1E4647145F70D9179F4666E3BE5F7A39FA83F2FADE}
I[2019-10-29|16:39:48.981] P2P Node ID                                  module=p2p ID=89a72a75ec65a45a21cc828038289f8e88654cc1 file=/home/ubuntu/.coinex/.cetd/config/node_key.json
I[2019-10-29|16:39:48.981] Adding persistent peers                      module=p2p addrs=[]
I[2019-10-29|16:39:48.981] Add our address to book                      module=p2p book=/home/ubuntu/.coinex/.cetd/config/addrbook.json addr=89a72a75ec65a45a21cc828038289f8e88654cc1@0.0.0.0:26656
I[2019-10-29|16:39:48.981] Starting Node                                module=node impl=Node
I[2019-10-29|16:39:48.981] Starting P2P Switch                          module=p2p impl="P2P Switch"
I[2019-10-29|16:39:48.982] Starting Reactor                             module=mempool impl=Reactor
I[2019-10-29|16:39:48.982] Starting BlockchainReactor                   module=blockchain impl=BlockchainReactor
I[2019-10-29|16:39:48.982] Starting BlockPool                           module=blockchain impl=BlockPool
I[2019-10-29|16:39:48.982] Starting ConsensusReactor                    module=consensus impl=ConsensusReactor
I[2019-10-29|16:39:48.982] ConsensusReactor                             module=consensus fastSync=true
I[2019-10-29|16:39:48.982] Starting EvidenceReactor                     module=evidence impl=EvidenceReactor
I[2019-10-29|16:39:48.982] Starting PEXReactor                          module=pex impl=PEXReactor
I[2019-10-29|16:39:48.982] Starting AddrBook                            module=p2p book=/home/ubuntu/.coinex/.cetd/config/addrbook.json impl=AddrBook
I[2019-10-29|16:39:48.982] Saving AddrBook to file                      module=p2p book=/home/ubuntu/.coinex/.cetd/config/addrbook.json size=0
I[2019-10-29|16:39:48.983] Starting RPC HTTP server on 127.0.0.1:26657  module=rpc-server
I[2019-10-29|16:39:49.000] Ensure peers                                 module=pex numOutPeers=0 numInPeers=0 numDialing=0 numToDial=10
I[2019-10-29|16:39:49.020] No addresses to dial. Falling back to seeds  module=pex
D[2019-10-29|16:39:50.026] Consensus ticker                             module=blockchain numPending=0 total=0 outbound=0 inbound=0
D[2019-10-29|16:39:50.026] Blockpool has no peers                       module=blockchain
D[2019-10-29|16:39:51.013] Consensus ticker                             module=blockchain numPending=0 total=0 outbound=0 inbound=0 
`
## cetcli status
`
{"node_info":{"protocol_version":{"p2p":"7","block":"10","app":"0"},"id":"89a72a75ec65a45a21cc828038289f8e88654cc1","listen_addr":"tcp://0.0.0.0:26656","network":"coinexdex-test2004","version":"0.32.2","channels":"4020212223303800","moniker":"wdfhl001","other":{"tx_index":"on","rpc_address":"tcp://127.0.0.1:26657"}},"sync_info":{"latest_block_hash":"","latest_app_hash":"","latest_block_height":"0","latest_block_time":"1970-01-01T00:00:00Z","catching_up":true},"validator_info":{"address":"749FB33317285CF866A37222FF9FBEC57ABA54FE","pub_key":{"type":"tendermint/PubKeyEd25519","value":"cCYCg9n1qFtOxTweRkcUX3DZF59GZuO+X3o5+oPy+t4="},"voting_power":"0"}}
`
按照你们文档一步步走下来的，麻烦看一下问题出在哪里

**Comment by zxh0** [comment]
@xiaogan18 来[coinex.org](https://www.coinex.org/)的[developer channel](https://join.slack.com/t/coinexchain/shared_invite/enQtNzA0NjU5ODc3MjM0LTk3NWUzMDA2YmU0NTc5MDg2NDI3NmRjM2VkNzYzNjIyZWM0NzZhMWIwMWQxNGJjNmI3NjVkZWIxZWUwNjJmYTI)讨论吧，这里沟通效率比较低。

**Comment by whitefen** [comment]
是否没填seeds？

**Comment by whunmr** [comment]
暂先关闭. 麻烦slack channel里沟通下具体问题. https://join.slack.com/t/coinexchain/shared_invite/enQtNzA0NjU5ODc3MjM0LTk3NWUzMDA2YmU0NTc5MDg2NDI3NmRjM2VkNzYzNjIyZWM0NzZhMWIwMWQxNGJjNmI3NjVkZWIxZWUwNjJmYTI
